website/views.py
from . import db
from .data_mapper import map_penalty_records, map_to_game_summary
from .models import UserEntity, GameEntity, GameStatus, PenaltyEntity, PenaltyRecordEntity, ParticipantStatus, ParticipantEntity, TotalFineEntity
from flask import Blueprint, render_template, request, flash, redirect, url_for, abort
from flask_login import login_required, current_user
import json


from .logger_config import setup_logger

DEBUG = True

class PlayerListError(ValueError):
    pass

logger = setup_logger()

views = Blueprint('views', __name__) # setup a blueprint for flask, can be named w.e. best practice to name same as file

# Display homepage endpoint
@views.route('/') # decorator
@login_required
def home():
    return render_template("home.html", user=current_user)

# Display user_management site
@views.route('/user_management', methods=['GET'])
@login_required
def user_management():
    participants = ParticipantEntity.query.filter_by(user_id=current_user.id, status = ParticipantStatus.active)
    return render_template("user_management.html", participants=participants, user=current_user)

# Display Game creation and loading site
@views.route('/create_or_load_game/', methods=['GET'])
@login_required
def create_or_load_game():
    participants = ParticipantEntity.query.filter_by(user_id=current_user.id, status = ParticipantStatus.active)
    all_saved_games = GameEntity.query.filter_by(user_id = current_user.id, status = GameStatus.active).all()
    len_all_saved_games = len(all_saved_games)
    logger.debug("Length of all saved_games for user {} is {}".format(current_user.email, len_all_saved_games))
    return render_template("create_or_load_game.html", game_participants=participants, user=current_user, all_saved_games = all_saved_games, len_all_saved_games=len_all_saved_games)

# Display certain game
@views.route('/view_game/<game_id>', methods=['GET'])
@login_required
def view_game(game_id):
    try:
        game = GameEntity.query.filter_by(id = game_id,user_id = current_user.id).one()
    except:
        flash("No game was found", category="error")
        return render_template("create_or_load_game.html",user=current_user)
    # game_participants is a json object storing all the player_ids as a string
    all_penalties = PenaltyEntity.query.filter_by(user_id=current_user.id).all()
    game_participants = game.game_participants
    if game_participants is None or game_participants == "":
        flash("invalid game", category="error")
        return render_template("create_or_load_game.html", user=current_user)
    logger.info("Game Status for user {} is {}".format(current_user.email,game.status))
    all_participant_ids = []
    if game.status == GameStatus.active:
        participants_data = []
        # Iterate through all participant ids
        # Get all their PenaltyRecordEntities from database
        # Get their TotalFine from database
        for player in json.loads(game_participants):
            all_participant_ids.append(int(player))
            participant_record = PenaltyRecordEntity.query.filter_by(game_id=game.id, participant_id=player).first()
            participant_fine_sum = TotalFineEntity.query.filter_by(game_id=game.id, participant_id=player).first()
            # Map the Database Entities to useful data_models, a single object that stores everything needed for the player
            # (name, quantity for each penalty, the total_finesum and more)
            # All stored in a list and given to the template
            participants_data.extend(map_penalty_records(participant_record, game_id,all_penalties, participant_fine_sum))
    if game.status == GameStatus.save:
        participants_data = []
        for player in json.loads(game_participants):
            all_participant_ids.append(player)
            participant_records = PenaltyRecordEntity.query.filter_by(game_id=game.id, participant_id=player).all()
            participant_fine_sum = TotalFineEntity.query.filter_by(game_id=game.id, participant_id=player).first()
            participants_data.append(map_to_game_summary(participant_records, participant_fine_sum))
        logger.debug("All participant_ids going into the game: ", all_participant_ids)
    return render_template("view_game.html",user=current_user, game=game, all_penalties=all_penalties, player_record_list = participants_data, all_participant_ids=all_participant_ids)

# Display finished game summary
@views.route('/game_summary/<game_id>', methods=['POST','GET'])
@login_required
def game_summary(game_id):
    if request.method != 'POST' and request.method !='GET':
        abort(405)
    # Create a game summary object and map everything so far obtained to it in the finish_game endpoint
    all_penalties = PenaltyEntity.query.filter_by(user_id = current_user.id).all()
    target_game = GameEntity.query.filter_by(id = game_id, user_id = current_user.id).first()
    if target_game and target_game.status == GameStatus.finish:
        game_participants = target_game.game_participants
        game_summary_objects = []
        for player in json.loads(game_participants):
            participant_records = PenaltyRecordEntity.query.filter_by(game_id=target_game.id, participant_id=player).all()
            participant_fine_sum = TotalFineEntity.query.filter_by(game_id=target_game.id, participant_id=player).first()
            game_summary_objects.append(map_to_game_summary(participant_records,participant_fine_sum))
        tier_list = retrieve_tier_list(game_summary_objects)
        penalty_sum = 1 + len(all_penalties)
        return render_template("game_summary.html", user= current_user, game = target_game, all_penalties = all_penalties, game_summary_objects = game_summary_objects, tier_list = tier_list, penalty_sum = penalty_sum)
    else:
        flash("This game has not been finished yet", category="error")

def retrieve_tier_list(PenaltyRecordList):
    max_quantities = {}
    for record in PenaltyRecordList:
        for penalty in record.penalties:
            if penalty.penalty_name not in max_quantities or max_quantities[penalty.penalty_name][1] < penalty.penalty_quantity:
                max_quantities[penalty.penalty_name] = (record.participant_name, penalty.penalty_quantity)
    return max_quantities

@views.route('/penalties', methods=['GET'])
@login_required
def penalties():
    penalties = PenaltyEntity.query.filter_by(user_id=current_user.id)
    return render_template("penalties.html", user=current_user, all_penalties = penalties)

@views.route('/view_archive', methods=['GET'])
@login_required
def view_archive():
    all_finished_games = GameEntity.query.filter_by(user_id = current_user.id, status = 'finish').all()
    return render_template("view_archive.html", user=current_user, all_finished_games = all_finished_games)

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="/static/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/static/css/fontawesome.min.css" />
    <link rel="stylesheet" href="/static/css/style.css" />
    <link rel="shortcut icon" href="/static/images/website-icon.png" />
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <!-- <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          {% if user.is_authenticated %}
          <a class="nav-item nav-link" id="home" href="/">Home</a>
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          {% else %}
          <a class="nav-item nav-link" id="login" href="/login">Login</a>
          <a class="nav-item nav-link" id="signup" href="/signup">Signup</a>
          {% endif %}
        </div>
      </div>
    </nav> -->
    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alert-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alert-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}
    <div class="container">
      {% block content %} {% endblock %}
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <footer>
        <div class="footer">
          <div class="footer-column">Contact</div>
          <div class="footer-column">About us</div>
          <div class="footer-column">
            <img
              src="/static/images/instagram.png"
              height="28px"
              width="25px"
            />
          </div>
        </div>
      </footer>
    </div>
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

website/templates/create_or_load_game.html
{% extends "base.html" %} {% block title %}Spieler Übersicht {% endblock %} {%
block content %}
<div style="flex: 1; margin: auto">
  <button
    style="outline: none; border: 0; background: none"
    onclick="location.href='/'"
  >
    <img
      src="/static/images/beer_landing_page_small_size.png"
      class="logo-picture"
    />
  </button>
</div>
<div style="display: flex; flex-wrap: wrap">
  <div style="flex: 1; margin: auto">
    <div id="wrapper">
      <form
        class="center"
        action="{{ url_for('configure.new_game') }}"
        method="POST"
      >
        <table class="list-column text-style">
          <thead>
          <th class="center" style="margin-top: 20px; font-weight: 600; font-size: 30px">
            Wer ist Anwesend?
          </th>
          <tr>
          </thead>
          <tbody>
            <td><br /></td>
          </tr>
          {% for player in game_participants %}
          <tr>
            <td>
              <div
                style="text-align: left; min-width: 100px">
                <input
                  class="checkbox"
                  type="checkbox"
                  value="{{ player.id }}"
                  name="players"
                  id="players"
                />
                <label for="active_players" style="width: 90px; word-wrap: break-word" {% if player.username|length > 7 %} class="long-text" {% endif %}>
              {{ player.username }}
                </div>
            </td>
            {% if loop.index % 2 == 1 %}
          </tr>
          {% endif %} {% endfor %}
            <tr><td><button type="submit" class="mt-2 mb-2 btn btn-primary">Bestätigen</button></td></tr>
        </tbody>
        </table>
      </form>
    </div>
  </div>
  <!-- XXX LOAD GAME FUNCTIONALITY NOT SHOWN UNTIL THIS IS FIXED -->
  <!-- <table class="mt-4 center table table-responsive list-column">
    <thead>
      <tr class="text-center text-style">
        <th>Gespeichertes Spiel laden</th>
      </tr>
    </thead>
    <tbody>
      {% for game in all_saved_games %}
      {% if len_all_saved_games > 0 %}
        <tr class="text-center text-style">
              <td style="vertical-align: middle;">
                <form action="{{ url_for('configure.load_game',game_id = game.id) }}"
                method="GET">
                <input type="hidden" name="id" value="{{ game.id }}">
                <input type="submit" class="archived_game_button" value="Spiel vom {{
                  game.date_created.strftime('%Y-%m-%d') }}">
              </form>
              </td>
        </tr>
      {% else %}
        <tr class="text-center text-style">
          <td style="vertical-align: middle;">
            <p>Keine Spiele gefunden</p>
          </td>
        </tr>
      {% endif %}
        {% endfor%}
    </tbody>
    </table> -->
</div>
{% endblock %}

website/templates/game_summary.html
{% extends "base.html" %} {% block title %} Kegelabend {{
  game.date_created.strftime('%Y-%m-%d') }} {% endblock %} {% block content %}
  <div style="flex: 1; margin: auto; padding: 15px">
    <button
      style="outline: none; border: 0; background: none"
      onclick="location.href='/'"
    >
      <img
        src="/static/images/beer_landing_page_small_size.png"
        class="logo-picture"
      />
    </button>
  </div>
<br>
<table class="table table-responsive">
    <thead>
      <th colspan="{{ penalty_sum }}">
        <h2 class="center"> Zusammenfassung </h2>
    </thead>
    <tbody>
      <tr class="text-center text-style">
        <td>Spieler</td>
        <td>Strafbetrag</td>
        {% for penalty in all_penalties %}
        <td>{{ penalty.title }}</td>
        {% endfor %}
        <td>Spieler</td>
      </tr>
      {% for summary_object in game_summary_objects %}
        <tr class="text-center text-style">
              <td style="vertical-align: middle;">
                {{summary_object.participant_name}}
              </td>
              <td>{{ summary_object.participant_total_fine.total_pay_amount }} €</td>
          {% for penalty in summary_object.penalties %}
          <td>
            <div >{{penalty.penalty_quantity}}</div>
          </td>
          {% endfor %}
          <td style="vertical-align: middle;">
            {{summary_object.participant_name}}
          </td>
        </tr>
        {% endfor%}
      </tr>
    </tbody>
  </table>
  <br>
  <br>
  <br>
  <!-- Rangliste sieht räudig aus aktuell, vielleicht anders bauen
  <table class="table table-bordered">
    <thead>
    <th colspan="3">
      <h2 class="center"> Rangliste </h2>
  </thead>
  <tbody>
  {% for penalty, (player_name, quantity) in tier_list.items() %}
  <tr  class="text-style">
    <td>
  {{ penalty }}
  </td>
  <td>{{ player_name }}</td>
  <td>{{ quantity }}</td>
</tr>
  {% endfor %}
</tbody>
</table>
<br> -->
  {% endblock %}

website/templates/home.html
{% extends "base.html" %} {% block title %}Home {% endblock %} {% block content
%}
<div style="display: flex; flex-wrap: wrap">
  <div style="flex: 1; margin: auto; padding: 15px">
    <button
      style="outline: none; border: 0; background: none"
      onclick="location.href='/'"
    >
      <img
        src="/static/images/beer_landing_page_small_size.png"
        class="logo-picture"
      />
    </button>
  </div>
</div>
<div style="display: flex; flex-wrap: wrap">
  <div style="flex: 1; margin: auto; padding: 15px">
    <div class="list-column menu_square">
      <a onclick="location.href='/view_archive'">
        <img
          src="/static/images/archive.png"
          alt="archiv"
          height="70"
          width="70"
        />
      </a>
      <p class="text-style">Archiv</p>
    </div>
    <div class="list-column menu_square">
      <a onclick="location.href='/penalties'">
        <img
          src="/static/images/penalties.png"
          alt="Penalties"
          height="70"
          width="70"
        />
      </a>
      <p class="text-style">Strafen</p>
    </div>
  </div>
</div>
<div style="display: flex; flex-wrap: wrap">
  <div style="flex: 1; margin: auto; padding: 15px">
    <div class="list-column menu_square">
      <a onclick="location.href='/create_or_load_game'">
        <img
          src="/static/images/trophy.png"
          alt="Games"
          height="70"
          width="70"
        />
      </a>
      <p class="text-style">Strichliste</p>
    </div>
    <div class="list-column menu_square">
      <a onclick="location.href='/user_management'">
        <img
          src="/static/images/add-user.png"
          alt="user-management"
          height="70"
          width="70"
        />
      </a>
      <p class="text-style">Spieler</p>
    </div>
  </div>
</div>
{% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}Login {% endblock %} {% block content
%}
<div class="mt-2 center" style="display: flex; flex-wrap: wrap">
  <div style="flex: 1; margin: auto">
    <button
      style="outline: none; border: 0; background: none"
      onclick="location.href='/signup'"
    >
      <img
        src="/static/images/beer_landing_page_small_size.png"
        class="logo-picture"
      />
    </button>
  </div>
  <form class="text-style" method="POST">
    <div class="form-group">
      <label for="email">E-Mail</label>
      <input
        type="email"
        class="mt-2 list-column form-control"
        id="email"
        name="email"
      />
      <label for="password">Password</label>
      <input
        type="password"
        class="mt-2 list-column form-control"
        id="password"
        name="password"
      />
      <button
        type="submit"
        class="form-control mt-4 list-column text-type btn btn-primary"
      >
        Login
      </button>
    </div>
  </form>
</div>
<br />
<br />
<br />
<br />

{% endblock %}

website/templates/penalties.html
{% extends "base.html" %} {% block title %}Penalties{% endblock %} {% block
content %}
<div style="display: flex; flex-wrap: wrap">
  <div style="flex: 1; margin: auto; padding: 15px">
    <button
      style="outline: none; border: 0; background: none"
      onclick="location.href='/'"
    >
      <img
        src="/static/images/beer_landing_page_small_size.png"
        class="logo-picture"
      />
    </button>
  </div>
</div>
<div class="center col-md-6">
  <form
    class="form-group text-style center"
    action="{{ url_for('configure.new_penalty') }}"
    method="POST"
  >
  <div>
    <label for="title">Title: </label>
    <input
      type="text"
      id="title"
      name="title"
      class="form-control list-column"
    />

  </div>
  <div>
    <label for="pay_amount">Pay Amount:</label>
    <input
      type="text"
      id="pay_amount"
      name="pay_amount"
      pattern="^[0-9]+(\.[0-9]{1,2})?$|^[0-9]{1,3}(,[0-9]{3})*(\.[0-9]{1,2})?$"
      required
      title="Please enter a valid pay amount in the format 0.20 or 0,20"
      class="form-control list-column"
    />
  </div>
    <div class="text-gray-500 mt-4">
      Invert? 
      <input
      class="checkbox"
      type="checkbox"
      id="invert"
      name="invert"
      title="Invert"
      />
      <br>(alle anderen müssen Zahlen)
    </div>
    <button class="list-column mt-4 btn btn-primary" type="submit">
      Create Penalty
    </button>
  </form>
</div>
<div class="table-responsive">
  <table
    class="table table-responsivelist-column form-check form-check-label"
    width="100%"
  >
    <thead style="width: 100%">
      <tr class="text-center text-style">
        <th>Title</th>
        <th>Fine</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody style="width: 100%">
      {% for penalty in all_penalties %}
      <tr class="text-center text-style" style="white-space: nowrap">
        <td>{{ penalty.title }}</td>
        <td>{{ penalty.pay_amount}} €</td>
        <td>
          <form
            action="{{ url_for('configure.delete_penalty', penalty_id=penalty.id) }}"
            method="POST"
          >
            <input type="hidden" name="id" value="{{ penalty.id }}" />
            <button type="submit" class="penalty-button btn-danger">X</button>
          </form>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

website/templates/signup.html
{% extends "base.html" %} {% block title %}Signup {% endblock %} {% block
content %}
<div class="mt-2 center" style="display: flex; flex-wrap: wrap">
  <div style="flex: 1; margin: auto">
    <button
      style="outline: none; border: 0; background: none"
      onclick="location.href='/login'"
    >
      <img
        src="/static/images/beer_landing_page_small_size.png"
        class="logo-picture"
      />
    </button>
  </div>
  <form class="text-style" method="POST">
    <div class="form-group">
      <label for="email">E-Mail</label>
      <input
        type="email"
        class="mt-2 list-column form-control"
        id="email"
        name="email"
      />
      <label for="firstName">Username</label>
      <input
        type="text"
        class="mt-2 list-column form-control"
        id="firstName"
        name="firstName"
      />
      <label for="password">Password</label>
      <input
        type="password"
        class="mt-2 list-column form-control"
        id="password1"
        name="password1"
      />
      <label for="password">Confirm Password</label>
      <input
        type="password"
        class="mt-2 list-column form-control"
        id="password2"
        name="password2"
      />
      <button
        type="submit"
        class="form-control mt-4 list-column text-type btn btn-primary"
      >
        Signup
      </button>
    </div>
  </form>
</div>
{% endblock %}

website/templates/user_management.html
{% extends "base.html" %} {% block title %} Spielermanagement {% endblock %} {%
block content %}
<div class="mt-4">
  <button
    style="outline: none; border: 0; background: none"
    onclick="location.href='/'"
  >
    <img
      src="/static/images/beer_landing_page_small_size.png"
      class="logo-picture"
    />
  </button>
  <form
    action="{{ url_for('configure.new_users') }}"
    method="POST"
    class="center"
  >
    <label
      class="mb-4 mt-4"
      style="
        font-family: 'Poppins';
        font-style: normal;
        font-weight: 600;
        font-size: 30px;
        line-height: 30px;
        color: #000000;
      "
      for="username"
      >Username:</label
    ><br />
    <input
      class="form-control list-column"
      type="text"
      id="username"
      name="username"
    /><br />
    <button
      id="username"
      type="submit"
      class="mt-2 list-column btn btn-primary mb-4"
    >
      Spieler hinzufügen
    </button>
  </form>
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr class="text-center text-style">
          <th>Username</th>
          <th>Delete</th>
        </tr>
      </thead>
      <tbody>
        {% for participant in participants %}
        <tr class="text-center text-style">
          <td>{{ participant.username }}</td>
          <td>
            <form
              action="{{ url_for('configure.delete_participant', participant_id = participant.id) }}"
              method="POST"
            >
              <input type="hidden" name="id" value="{{ participant.id }}" />
              <button type="submit" class="user-delete-btn btn btn-danger">
                X
              </button>
            </form>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

website/templates/view_archive.html
{% extends "base.html" %} {% block title %}Spieler Übersicht {% endblock %} {%
block content %}
<div style="flex: 1; margin: auto; padding: 15px">
  <button
    style="outline: none; border: 0; background: none"
    onclick="location.href='/'"
  >
    <img
      src="/static/images/beer_landing_page_small_size.png"
      class="logo-picture"
    />
  </button>

  <table class="center table table-responsive">
    <thead>
      <tr class="text-center text-style">
        <th>Abgeschlossene Spiele</th>
      </tr>
    </thead>
    <tbody>
      {% for game in all_finished_games %}
      <tr class="text-center text-style">
        <td style="vertical-align: middle">
          <form
            action="{{ url_for('views.game_summary',game_id = game.id) }}"
            method="POST"
          >
            <input type="hidden" name="id" value="{{ game.id }}" />
            <input
              type="submit"
              class="archived_game_button"
              value="Abend vom {{
                  game.date_created.strftime('%Y-%m-%d') }}"
            />
          </form>
        </td>
        <td>
          <form
            action="{{ url_for('configure.delete_game', game_id = game.id) }}"
            method="POST"
          >
            <input type="hidden" name="id" value="{{ game.id }}" />
            <button type="submit" class="penalty-button btn-danger">X</button>
          </form>
        </td>
      </tr>
      {% endfor%}
    </tbody>
  </table>
</div>
{% endblock %}

website/templates/view_game.html
{% extends "base.html" %} {% block title %} Kegelabend {{
game.date_created.strftime('%Y-%m-%d') }} {% endblock %} {% block content %}
<script src="/static/js/game_configuration.js"></script>
<script src="/static/js/NoSleep.js"></script>
<table class="table table-responsive">
  <thead>
    <tr class="text-center text-style">
      <th colspan="{{ all_penalties|length + 2 }}">Gametable</th>
    </tr>
  </thead>
  <tbody>
    {% for player_record in player_record_list %} {% set avatar_path =
    '/static/images/profile_avatars/avatar' + player_record.avatar_index|string
    + '.png' %}
    <tr class="text-center text-style">
      <td style="vertical-align: middle">
        <div
          onclick="toggleUserPenalties('{{ player_record.game_id}}-{{ player_record.participant_id }}-tablecell')"
          class="player-square square-border"
        >
          <img src="{{ avatar_path }}" alt="Avatar" class="avatar-image" />
        </div>
        <a class="participant_name">{{player_record.participant_name}}</a>
      </td>
      {% for penalty in player_record.penalties %}
      <td
        class="hideRow"
        id="{{ player_record.game_id}}-{{ player_record.participant_id }}-tablecell"
        style="min-width: 150px"
      >
        <br />
        {{penalty.penalty_name}}
        <br />
        <div
          id="{{player_record.game_id}}-{{penalty.id}}-{{player_record.participant_id}}-{{penalty.penalty_amount}}-penalty-quantity"
        >
          {{penalty.penalty_quantity}}
        </div>
        <button
          id="{{player_record.game_id}}-{{ penalty.id}}-{{player_record.participant_id}}-add"
          {% if not penalty.invert %}
          onclick="updateQuantity('{{ player_record.game_id }}-{{ penalty.id}}-{{player_record.participant_id}}-{{penalty.penalty_amount}}-add-{{ penalty.invert }}')"
          {% else %}
          onclick="updateQuantity('{{ player_record.game_id }}-{{ penalty.id}}-{{player_record.participant_id}}-{{penalty.penalty_amount}}-add-{{ penalty.invert }}-{{all_participant_ids}}')"
          {% endif %}
          class="quantity-up-button"
          style="height: 40px; width: 40px; background-color: lightgreen"
          type="submit"
        >
          &#43;
        </button>
        <button
          id="{{player_record.game_id}}-{{ penalty.id}}-{{player_record.participant_id}}-subtract-{{ penalty.invert }}"
          {%
          if
          not
          penalty.invert
          %}
          onclick="updateQuantity('{{ player_record.game_id }}-{{ penalty.id}}-{{player_record.participant_id}}-{{penalty.penalty_amount}}-subtract-{{ penalty.invert }}')"
          {%
          else
          %}
          onclick="updateQuantity('{{ player_record.game_id }}-{{ penalty.id}}-{{player_record.participant_id}}-{{penalty.penalty_amount}}-subtract-{{ penalty.invert }}-{{all_participant_ids}}')"
          {%
          endif
          %}
          class="quantity-down-button"
          style="height: 40px; width: 40px; background-color: #f87217"
          type="submit"
        >
          &#8722;
        </button>
      </td>
      {% endfor %}
      <td>
        <div
          id="{{ player_record.game_id }}-{{ player_record.participant_id }}-total-fine"
          style="vertical-align: middle"
        >
          <br />{{player_record.participant_total_fine.total_pay_amount|
          default(0)}} €
        </div>
      </td>
    </tr>
    {% endfor%}
  </tbody>
</table>
<form
  action="{{ url_for('configure.finish_game', game_id = game.id) }}"
  method="POST"
>
  <button onclick="noSleep.disable()" type="submit" class="mb-4 game-finish-btn btn-primary">
    Abend beenden
  </button>
</form>
{% endblock %}